Rename get_docker_image_manifests to get_docker_image_manifest_list. Also documentation changes

diff --git a/docker_registry_api_bash_functions b/docker_registry_api_bash_functions
--- a/docker_registry_api_bash_functions
+++ b/docker_registry_api_bash_functions
@@ -604,19 +604,19 @@ function get_docker_image_manifest() {
 
 
 ############################################################################################################################################################
-# Function to display the usage for the get_docker_image_manifests() function.
+# Function to display the usage for the get_docker_image_manifest_list() function.
 ############################################################################################################################################################
-function usage_get_docker_image_manifests() {
-    printf 'Usage: get_docker_image_manifests -i docker-image [-t {image|plugin}] [-k]\n' >&2
+function usage_get_docker_image_manifest_list() {
+    printf 'Usage: get_docker_image_manifest_list -i docker-image [-t {image|plugin}] [-k]\n' >&2
     printf ' -i is the Docker Image and must be specified.\n' >&2
     printf ' -t {image|plugin} Default is image\n' >&2
     printf ' -k disable SSL verification for an insecure private Docker Trusted Registry\n' >&2
 }
 
 ############################################################################################################################################################
-# Function to get the Docker image manifest for a Docker image.
+# Function to get the Docker image Manifest List for a Docker image.
 ############################################################################################################################################################
-function get_docker_image_manifests() {
+function get_docker_image_manifest_list() {
 
     ########################################################################################################################################################
     # Get the command line arguments.
@@ -638,11 +638,11 @@ function get_docker_image_manifests() {
                 INSECURE="-k"           
                 ;;    
             h)                                          # -h help
-                usage_get_docker_image_manifests
+                usage_get_docker_image_manifest_list
                 return 1
                 ;;
             \?)
-                usage_get_docker_image_manifests
+                usage_get_docker_image_manifest_list
                 return 1
                 ;;
         esac
@@ -657,7 +657,7 @@ function get_docker_image_manifests() {
         TYPE=$(echo "$TYPE" | awk '{print tolower($0)}')
         if [[ $TYPE != 'image' && $TYPE != 'plugin' ]]; then
             printf "The type value ${TYPE} is invalid.  Must be image or plugin!\n" >&2
-            usage_get_docker_image_manifests
+            usage_get_docker_image_manifest_list
             return 1
         fi                
     fi   
@@ -667,7 +667,7 @@ function get_docker_image_manifests() {
     ########################################################################################################################################################
     if [[ -z $DOCKER_IMAGE ]]; then
         printf 'You must specify a Docker Image!\n' >&2
-        usage_get_docker_image_manifests
+        usage_get_docker_image_manifest_list
         return 1
     fi    
 
@@ -677,7 +677,7 @@ function get_docker_image_manifests() {
     local DOCKER_REPO=$(echo $DOCKER_IMAGE | awk -F':' '{print $1}')
     if [[ -z $DOCKER_REPO ]]; then
         printf 'You must specify a Docker Repo!\n' >&2
-        usage_get_docker_image_manifests
+        usage_get_docker_image_manifest_list
         return 1
     fi
 
@@ -686,7 +686,7 @@ function get_docker_image_manifests() {
     ########################################################################################################################################################
     if [[ $DOCKER_REPO != */* ]]; then
         printf '\nYou did not prefix the Docker Image with a user name (username/, library/ or dockerstorestaging/)!\n' >&2
-        usage_get_docker_image_manifests
+        usage_get_docker_image_manifest_list
         return 1
     fi
 
@@ -696,7 +696,7 @@ function get_docker_image_manifests() {
     local DOCKER_IMAGE_TAG=$(echo $DOCKER_IMAGE | awk -F':' '{print $2}')
     if [[ -z $DOCKER_IMAGE_TAG ]]; then
         printf '\nYou did not specify a tag for the Docker Image!\n' >&2
-        usage_get_docker_image_manifests
+        usage_get_docker_image_manifest_list
         return 1
     fi
 
@@ -719,20 +719,20 @@ function get_docker_image_manifests() {
     fi
 
     ########################################################################################################################################################
-    # Call the Docker Registry API to retrieve the Manifests for the Docker Image.
+    # Call the Docker Registry API to retrieve the Manifest List for the Docker Image.
     ########################################################################################################################################################
-    local MANIFEST_HEADER='application/vnd.docker.distribution.manifest.list.v2+json'
+    local MANIFEST_HEADER='application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.plugin.v1+json'
     local OUTPUT=$(curl -S --silent ${INSECURE} --header "Authorization: BEARER ${TOKEN}" --header "Accept: ${MANIFEST_HEADER}" \
     --write-out "\n%{http_code}" "${DOCKER_REGISTRY_API_ENDPOINT}/v2/${DOCKER_REPO}/manifests/${DOCKER_IMAGE_TAG}")
     local HTTP_CODE=$(echo "$OUTPUT" | awk 'END{print}')
     if [[ "$HTTP_CODE" != "200" ]]; then
-        printf 'Unable to get the Docker Image manifest for the Docker Image %s!\n' "${DOCKER_REPO}:${DOCKER_IMAGE_TAG}" >&2 
+        printf 'Unable to get the Docker Image Manifest List for the Docker Image %s!\n' "${DOCKER_REPO}:${DOCKER_IMAGE_TAG}" >&2 
         printf "${DOCKER_REGISTRY_API_ENDPOINT}/v2/${DOCKER_REPO}/manifests/${DOCKER_IMAGE_TAG}\n" >&2
         print_docker_registry_api_error "${OUTPUT}"
         return 1
     else
-        local DOCKER_IMAGE_MANIFEST=$(echo "$OUTPUT" | awk 'NR > 1 { print prev } { prev = $0 }')
-        printf '%s\n' "${DOCKER_IMAGE_MANIFEST}"
+        local DOCKER_IMAGE_MANIFEST_LIST=$(echo "$OUTPUT" | awk 'NR > 1 { print prev } { prev = $0 }')
+        printf '%s\n' "${DOCKER_IMAGE_MANIFEST_LIST}"
         return 0
     fi
 }
@@ -889,5 +889,5 @@ export -f get_docker_registry_api_token
 export -f get_docker_repo_tags
 export -f get_docker_image_content_digest
 export -f get_docker_image_manifest
-export -f get_docker_image_manifests
+export -f get_docker_image_manifest_list
 export -f get_docker_image_config_blob
